const mongoose=require("mongoose")
const HospitalSchema=new mongoose.Schema({
    name:{
        type:String,
        required:true
    },
    pincode:{
        type:String,
        required:true
    },
    phone:{
        type:String,
        required:true
    },
    emergency:{
        type:String,
        required:true
    },
    email:{
        type:String,
        required:true
    },
    address:{
        type:String,
        required:true
    },
    state:{
        type:String,
        required:true
    },
    district:{
        type:String,
        required:true
    },
    password:{
        type:String,
        required:true
    },
    confirmPassword:{
        type:String
    }
})
const HospitalRegister=mongoose.model('Hospital',HospitalSchema);
module.exports=HospitalRegister;